#!/bin/bash

if [ "$EUID" -ne 0 ]; then
        echo "you are not root, come back when you are, BYE"
        exit
fi


#get param
zone=$1

FILENAME='db.'"$zone"'.eline-schepers.sb.uclllabs.be'
FILE=/etc/bind/zones/$FILENAME
if test -f "$FILE"; then
        echo 'the zone '"$1"' already exists, try another one!'
else


#named.conf.local
input="/etc/bind/named.conf.local"
echo 'zone "'"$zone"'.eline-schepers.sb.uclllabs.be" {
        type master;
        file "/etc/bind/zones/'"$FILENAME"'";
};
' >> $input

#db.zone
output=/etc/bind/zones/$FILENAME
echo '
$TTL 300     ;86400
$ORIGIN '"$zone"'.eline-schepers.sb.uclllabs.be.
@       IN      SOA    ns.'"$zone"'.eline-schepers.sb.uclllabs.be. root.eline-schepers.sb.uclllabs.be. (
                                10              ;Serial
                                604800          ;Refresh
                                86400           ;Retry
                                2419200         ;Expire
                                86400 )         ;Negative Cache TTL
;Name servers
@       IN      NS      ns.eline-schepers.sb.uclllabs.be.
;A records
ns      IN       A      193.191.177.143
@       IN       A      193.191.177.143
' >> $output

#db.eline-schepers
DBFILE=/etc/bind/db.eline-schepers.sb.uclllabs.be
echo "$zone"'	IN	NS	ns.eline-schepers.sb.uclllabs.be.' >> $DBFILE

#db serial serial
Serial=$(grep 'Serial' /etc/bind/db.eline-schepers.sb.uclllabs.be)
SerialNumber=$(echo $Serial | sed 's/[^0-9]*//g')
((SerialNumber++))
newSerial='                                '"$SerialNumber"'        ;Serial'
sed -i "s/.*Serial.*/\t\t\t      $newSerial/g" /etc/bind/db.eline-schepers.sb.uclllabs.be



systemctl restart bind9


fi
